2022-08-01 07:41:22,318 ERROR: Exception on /unfollow/susan [POST] [in /usr/local/lib/python3.9/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'unfollow' did not return a valid response. The function either returned None or ended without a return statement.
2022-08-01 07:42:20,175 INFO: Microblog startup [in /root/python/flask/app/__init__.py:45]
2022-08-01 07:45:21,738 INFO: Microblog startup [in /root/python/flask/app/__init__.py:45]
2022-08-01 07:46:19,800 INFO: Microblog startup [in /root/python/flask/app/__init__.py:45]
2022-08-01 07:47:04,597 INFO: Microblog startup [in /root/python/flask/app/__init__.py:45]
2022-08-01 08:02:24,954 INFO: Microblog startup [in /root/python/flask/app/__init__.py:45]
2022-08-01 08:40:39,718 INFO: Microblog startup [in /root/python/flask/app/__init__.py:47]
2022-08-01 08:48:36,038 INFO: Microblog startup [in /root/python/flask/app/__init__.py:47]
2022-08-01 08:55:19,902 INFO: Microblog startup [in /root/python/flask/app/__init__.py:47]
2022-08-01 09:01:11,305 INFO: Microblog startup [in /root/python/flask/app/__init__.py:47]
2022-08-01 09:05:19,292 INFO: Microblog startup [in /root/python/flask/app/__init__.py:47]
2022-08-01 09:13:37,422 INFO: Microblog startup [in /root/python/flask/app/__init__.py:47]
2022-08-01 09:13:43,680 ERROR: Exception on /register [GET] [in /usr/local/lib/python3.9/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/root/python/flask/app/routes.py", line 68, in register
    return render_template('register.html',title='Register',form=form)
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/root/python/flask/app/templates/register.html", line 2, in template
    {% import 'bootstrap/wtf.html as wtf %}
jinja2.exceptions.TemplateSyntaxError: unexpected char "'" at 36
2022-08-01 09:16:25,096 INFO: Microblog startup [in /root/python/flask/app/__init__.py:47]
2022-08-02 04:57:40,860 INFO: Microblog startup [in /root/python/flask/app/__init__.py:49]
2022-08-02 04:57:49,108 ERROR: Exception on /user/buben [GET] [in /usr/local/lib/python3.9/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/root/python/flask/app/routes.py", line 82, in user
    return render_template('user.html',user=user,posts=posts.items,
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/root/python/flask/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/root/python/flask/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/usr/local/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/usr/local/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/usr/local/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/usr/local/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/root/python/flask/app/templates/base.html", line 53, in block 'content'
    {% block app_content %}{% endblock %}
  File "/root/python/flask/app/templates/user.html", line 10, in block 'app_content'
    {% if user.last_seen %}<p>Last seen on: {{ moment(user.last_seem).format('LLL') }}</p>{% endif %}
  File "/usr/local/lib/python3.9/site-packages/flask_moment/__init__.py", line 212, in format
    return self._render("format", format=(fmt or ''), refresh=refresh)
  File "/usr/local/lib/python3.9/site-packages/flask_moment/__init__.py", line 186, in _render
    t = self._timestamp_as_iso_8601(self.timestamp)
  File "/usr/local/lib/python3.9/site-packages/flask_moment/__init__.py", line 182, in _timestamp_as_iso_8601
    return timestamp.strftime('%Y-%m-%dT%H:%M:%S' + tz)
jinja2.exceptions.UndefinedError: 'app.models.User object' has no attribute 'last_seem'
2022-08-02 04:58:06,764 INFO: Microblog startup [in /root/python/flask/app/__init__.py:49]
2022-08-02 05:02:31,561 INFO: Microblog startup [in /root/python/flask/app/__init__.py:49]
2022-08-02 06:13:23,159 INFO: Microblog startup [in /root/python/flask/app/__init__.py:52]
2022-08-02 06:13:32,291 INFO: Microblog startup [in /root/python/flask/app/__init__.py:52]
2022-08-02 06:18:40,267 INFO: Microblog startup [in /root/python/flask/app/__init__.py:52]
2022-08-02 08:04:51,099 INFO: Microblog startup [in /root/python/flask/app/__init__.py:52]
2022-08-02 08:05:25,841 INFO: Microblog startup [in /root/python/flask/app/__init__.py:52]
2022-08-02 08:05:52,870 INFO: Microblog startup [in /root/python/flask/app/__init__.py:52]
2022-08-02 08:06:14,460 INFO: Microblog startup [in /root/python/flask/app/__init__.py:52]
2022-08-02 08:06:26,938 INFO: Microblog startup [in /root/python/flask/app/__init__.py:52]
2022-08-03 04:39:07,566 INFO: Microblog startup [in /root/python/flask/app/__init__.py:52]
